/// <reference lib="webworker" />
import { setCacheNameDetails } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute, setCatchHandler } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

declare let self: ServiceWorkerGlobalScope;

setCacheNameDetails({
  prefix: 'globalcart',
  suffix: 'v1',
  precache: 'precache',
  runtime: 'runtime'
});

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// Offline fallback for SPA
try {
  const handler = createHandlerBoundToURL('/index.html');
  const navigationRoute = new NavigationRoute(handler, {
    denylist: [
      new RegExp('/api/.*'),
    ],
  });
  registerRoute(navigationRoute);
} catch (e) {
  console.log('Error registering NavigationRoute', e);
}

// Set catch handler for offline fallback
setCatchHandler(async ({ event }) => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if ((event as any).request.destination === 'document') {
    return (await caches.match('/offline.html', { ignoreSearch: true })) || Response.error();
  }
  return Response.error();
});

// Background Sync for API requests
const bgSyncPlugin = new BackgroundSyncPlugin('api-queue', {
  maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
});

registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'GET',
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      bgSyncPlugin
    ]
  })
);

// Cache Google Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365,
        maxEntries: 30,
      }),
    ],
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Handle Push Notifications
self.addEventListener('push', (event) => {
  let data = {};
  try {
    data = event.data ? event.data.json() : {};
  } catch (e) {
    console.log('Push event data is not JSON', e);
    data = { title: 'Notification', body: event.data ? event.data.text() : '' };
  }
  
  const title = data.title || 'GlobalCart Reseller';
  const options = {
    body: data.body || 'You have a new update!',
    icon: '/brand/icon-192.png',
    badge: '/brand/icon-192.png',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/'
    },
    actions: [
      { action: 'open', title: 'Open App' },
      { action: 'close', title: 'Close' }
    ]
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  if (event.action === 'close') return;

  const urlToOpen = event.notification.data.url || '/';
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Handle Background Sync (Custom tags)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-orders') {
    console.log('Syncing orders...');
    // Implementation for syncing orders would go here
  }
});

// Handle Periodic Background Sync
// eslint-disable-next-line @typescript-eslint/no-explicit-any
self.addEventListener('periodicsync', (event: any) => {
  if (event.tag === 'fetch-latest-products') {
    console.log('Fetching latest products in background...');
    // Implementation for periodic sync would go here
  }
});

// Explicit fetch listener to help PWA detection tools
self.addEventListener('fetch', (event) => {
  // Workbox handles most of this via registerRoute, 
  // but having an explicit listener can sometimes help detection
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request).catch(() => {
        return caches.match('/offline.html', { ignoreSearch: true })
          .then(response => response || caches.match('/index.html', { ignoreSearch: true }))
          .then(response => response || Response.error());
      })
    );
  }
});

// Allow the service worker to take control of the page immediately
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
